RepairEquipment/Models/Order.cs
using System;
using System.Collections.Generic;

namespace RepairEquipment.Models
{
    public class Order
    {
        public int OrderId { get; set; }
        public DateTime OrderDate { get; set; }
        public string SerialNumber { get; set; }
        public DateTime ReturnDate { get; set; }
        public string WarrantyNote { get; set; }
        public DateTime WarrantyRepairPeriod { get; set; }
        public int EmployeeId { get; set; }
        public int ModelId { get; set; }
        public int CustomerId { get; set; }

        public virtual Employee Employee { get; set; }
        public virtual Model Model { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual ICollection<Spare> Spares { get; set; }
        public virtual ICollection<Malfunction> Malfunctions { get; set; }

        public Order()
        {
            Spares = new List<Spare>();
            Malfunctions = new List<Malfunction>();
        }
    }
}

RepairEquipment/Controllers/OrderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using RepairEquipment.Models;
using PagedList.Core;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Authorization;

namespace RepairEquipment.Controllers
{
    [Authorize]
    public class OrderController : Controller
    {
        RepairEquipmentContext db;

        public OrderController(RepairEquipmentContext context)
        {
            db = context;
        }

        // GET: Order
        public ActionResult Index(int? page, string searchString)
        {
            int pageSize = 10;
            int pageNumber = (page ?? 1);

            var order = db.Orders.OrderBy(t => t.OrderId).Include(t => t.Employee).Include(t => t.Model).Include(t => t.Customer).ToPagedList(pageNumber, pageSize);

            if (!String.IsNullOrEmpty(searchString))
            {
                order = db.Orders.Where(t => t.SerialNumber.Contains(searchString)).OrderBy(t => t.OrderId).Include(t => t.Employee).Include(t => t.Model).Include(t => t.Customer).ToPagedList(pageNumber, pageSize);
            }

            return View(order);
        }

        // GET: Order/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new StatusCodeResult(StatusCodes.Status400BadRequest);
            }
            Order order = db.Orders.Find(id);
            if (order == null)
            {
                return NotFound();
            }
            return View(order);
        }

        // GET: Order/Create
        public ActionResult Create()
        {
            ViewBag.ModelId = new SelectList(db.Models, "ModelId", "Name");
            ViewBag.EmployeeId = new SelectList(db.Employees, "EmployeeId", "FullName");
            ViewBag.CustomerId = new SelectList(db.Customers, "CustomerId", "FullName");
            return View();
        }

        // POST: Order/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind("OrderId", "OrderDate", "SerialNumber", "ReturnDate", "WarrantyNote", "WarrantyRepairPeriod", "EmployeeId", "ModelId", "CustomerId")] Order order)
        {
            if (ModelState.IsValid)
            {
                db.Orders.Add(order);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.ModelId = new SelectList(db.Models, "ModelId", "Name", order.ModelId);
            ViewBag.EmployeeId = new SelectList(db.Employees, "EmployeeId", "FullName", order.EmployeeId);
            ViewBag.CustomerId = new SelectList(db.Customers, "CustomerId", "FullName", order.CustomerId);
            return View(order);
        }

        // GET: Order/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new StatusCodeResult(StatusCodes.Status400BadRequest);
            }
            Order order = db.Orders.Find(id);
            if (order == null)
            {
                return NotFound();
            }
            ViewBag.ModelId = new SelectList(db.Models, "ModelId", "Name", order.ModelId);
            ViewBag.EmployeeId = new SelectList(db.Employees, "EmployeeId", "FullName", order.EmployeeId);
            ViewBag.CustomerId = new SelectList(db.Customers, "CustomerId", "FullName", order.CustomerId);
            return View(order);
        }

        // POST: Order/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind("OrderId", "OrderDate", "SerialNumber", "ReturnDate", "WarrantyNote", "WarrantyRepairPeriod", "EmployeeId", "ModelId", "CustomerId")] Order order)
        {
            if (ModelState.IsValid)
            {
                db.Entry(order).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ModelId = new SelectList(db.Models, "ModelId", "Name", order.ModelId);
            ViewBag.EmployeeId = new SelectList(db.Employees, "EmployeeId", "FullName", order.EmployeeId);
            ViewBag.CustomerId = new SelectList(db.Customers, "CustomerId", "FullName", order.CustomerId);
            return View(order);
        }

        // GET: Order/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new StatusCodeResult(StatusCodes.Status400BadRequest);
            }
            Order order = db.Orders.Find(id);
            if (order == null)
            {
                return NotFound();
            }
            return View(order);
        }

        // POST: Order/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            Order order = db.Orders.Find(id);
            db.Orders.Remove(order);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

RepairEquipment/Views/Order/Create.cshtml
@model RepairEquipment.Models.Order

@{
    ViewData["Title"] = "Create";
}

<h2>Добавить запись</h2>

<form asp-action="Create">
    <div class="form-horizontal">
        <h4>Заказ</h4>
        <hr />
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group">
            <label asp-for="OrderDate" class="col-md-2 control-label">Дата заказа</label>
            <div class="col-md-10">
                <input asp-for="OrderDate" class="form-control" />
                <span asp-validation-for="OrderDate" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="SerialNumber" class="col-md-2 control-label">Серийный номер</label>
            <div class="col-md-10">
                <input asp-for="SerialNumber" class="form-control" />
                <span asp-validation-for="SerialNumber" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="ReturnDate" class="col-md-2 control-label">Дата возврата</label>
            <div class="col-md-10">
                <input asp-for="ReturnDate" class="form-control" />
                <span asp-validation-for="ReturnDate" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="WarrantyNote" class="col-md-2 control-label">Гарантийная отметка</label>
            <div class="col-md-10">
                <input asp-for="WarrantyNote" class="form-control" />
                <span asp-validation-for="WarrantyNote" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="WarrantyRepairPeriod" class="col-md-2 control-label">Окончание гарантии</label>
            <div class="col-md-10">
                <input asp-for="WarrantyRepairPeriod" class="form-control" />
                <span asp-validation-for="WarrantyRepairPeriod" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="EmployeeId" class="col-md-2 control-label">Рабочий</label>
            <div class="col-md-10">
                @Html.DropDownList("EmployeeId", null, htmlAttributes: new { @class = "form-control" })
                <span asp-validation-for="EmployeeId" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="ModelId" class="col-md-2 control-label">Модель</label>
            <div class="col-md-10">
                @Html.DropDownList("ModelId", null, htmlAttributes: new { @class = "form-control" })
                <span asp-validation-for="ModelId" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="CustomerId" class="col-md-2 control-label">Заказчик</label>
            <div class="col-md-10">
                @Html.DropDownList("CustomerId", null, htmlAttributes: new { @class = "form-control" })
                <span asp-validation-for="CustomerId" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Добавить" class="btn btn-default" />
            </div>
        </div>
    </div>
</form>

<div>
    <a asp-action="Index">Вернуться</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

RepairEquipment/Views/Order/Delete.cshtml
@model RepairEquipment.Models.Order

@{
    ViewData["Title"] = "Delete";
}

<h2>Удаление записи</h2>

<h3>Вы уверены, что хотите удалить эту запись?</h3>
<div>
    <h4>Заказ</h4>
    <hr />
    <dl class="dl-horizontal">
        <input type="hidden" asp-for="OrderId" />
        <dt>
            Номер заказа
        </dt>
        <dd>
            @Html.DisplayFor(model => model.OrderId)
        </dd>
        <dt>
            Дата заказа
        </dt>
        <dd>
            @Html.DisplayFor(model => model.OrderDate)
        </dd>
        <dt>
            Серийный номер
        </dt>
        <dd>
            @Html.DisplayFor(model => model.SerialNumber)
        </dd>
        <dt>
            Дата возврата
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ReturnDate)
        </dd>
        <dt>
            Гарантийная отметка
        </dt>
        <dd>
            @Html.DisplayFor(model => model.WarrantyNote)
        </dd>
        <dt>
            Окончание гарантии
        </dt>
        <dd>
            @Html.DisplayFor(model => model.WarrantyRepairPeriod)
        </dd>
        <dt>
            Рабочий
        </dt>
        <dd>
            @Html.DisplayFor(model => model.EmployeeId)
        </dd>
        <dt>
            Модель
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ModelId)
        </dd>
        <dt>
            Заказчик
        </dt>
        <dd>
            @Html.DisplayFor(model => model.CustomerId)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <div class="form-actions no-color">
            <input type="submit" value="Удалить" class="btn btn-default" /> |
            <a asp-action="Index">Вернуться</a>
        </div>
    </form>
</div>

RepairEquipment/Views/Order/Details.cshtml
@model RepairEquipment.Models.Order

@{
    ViewData["Title"] = "Details";
}

<h2>Детали</h2>

<div>
    <h4>Заказ</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Номер заказа
        </dt>
        <dd>
            @Html.DisplayFor(model => model.OrderId)
        </dd>
        <dt>
            Дата заказа
        </dt>
        <dd>
            @Html.DisplayFor(model => model.OrderDate)
        </dd>
        <dt>
            Серийный номер
        </dt>
        <dd>
            @Html.DisplayFor(model => model.SerialNumber)
        </dd>
        <dt>
            Дата возврата
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ReturnDate)
        </dd>
        <dt>
            Гарантийная отметка
        </dt>
        <dd>
            @Html.DisplayFor(model => model.WarrantyNote)
        </dd>
        <dt>
            Окончание гарантии
        </dt>
        <dd>
            @Html.DisplayFor(model => model.WarrantyRepairPeriod)
        </dd>
        <dt>
            Рабочий
        </dt>
        <dd>
            @Html.DisplayFor(model => model.EmployeeId)
        </dd>
        <dt>
            Модель
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ModelId)
        </dd>
        <dt>
            Заказчик
        </dt>
        <dd>
            @Html.DisplayFor(model => model.CustomerId)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.OrderId">Редактировать</a> |
    <a asp-action="Index">Вернуться</a>
</div>

RepairEquipment/Views/Order/Edit.cshtml
@model RepairEquipment.Models.Order

@{
    ViewData["Title"] = "Edit";
}

<h2>Редактирование записи</h2>

<form asp-action="Edit">
    <div class="form-horizontal">
        <h4>Заказ</h4>
        <hr />
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <input type="hidden" asp-for="OrderId" />
        <div class="form-group">
            <label asp-for="OrderDate" class="col-md-2 control-label">Дата заказа</label>
            <div class="col-md-10">
                <input asp-for="OrderDate" class="form-control" />
                <span asp-validation-for="OrderDate" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="SerialNumber" class="col-md-2 control-label">Серийный номер</label>
            <div class="col-md-10">
                <input asp-for="SerialNumber" class="form-control" />
                <span asp-validation-for="SerialNumber" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="ReturnDate" class="col-md-2 control-label">Дата возврата</label>
            <div class="col-md-10">
                <input asp-for="ReturnDate" class="form-control" />
                <span asp-validation-for="ReturnDate" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="WarrantyNote" class="col-md-2 control-label">Гарантийная отметка</label>
            <div class="col-md-10">
                <input asp-for="WarrantyNote" class="form-control" />
                <span asp-validation-for="WarrantyNote" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="WarrantyRepairPeriod" class="col-md-2 control-label">Окончание гарантии</label>
            <div class="col-md-10">
                <input asp-for="WarrantyRepairPeriod" class="form-control" />
                <span asp-validation-for="WarrantyRepairPeriod" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="EmployeeId" class="col-md-2 control-label">Рабочий</label>
            <div class="col-md-10">
                @Html.DropDownList("EmployeeId", null, htmlAttributes: new { @class = "form-control" })
                <span asp-validation-for="EmployeeId" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="ModelId" class="col-md-2 control-label">Модель</label>
            <div class="col-md-10">
                @Html.DropDownList("ModelId", null, htmlAttributes: new { @class = "form-control" })
                <span asp-validation-for="ModelId" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="CustomerId" class="col-md-2 control-label">Заказчик</label>
            <div class="col-md-10">
                @Html.DropDownList("CustomerId", null, htmlAttributes: new { @class = "form-control" })
                <span asp-validation-for="CustomerId" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
</form>

<div>
    <a asp-action="Index">Вернуться</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

RepairEquipment/Views/Order/Index.cshtml
@using PagedList.Core;

@model IPagedList<RepairEquipment.Models.Order>

@{
    ViewData["Title"] = "List";
}

<h2>Заказы</h2>

<p>
    <a asp-action="Create">Добавить запись</a>
</p>
<table class="table">
    <thead>
        <tr>
                <th>
                    Номер заказа
                </th>
                <th>
                    Дата заказа
                </th>
                <th>
                    Серийный номер
                </th>
                <th>
                    Дата возврата
                </th>
                <th>
                    Гарантийная отметка
                </th>
                <th>
                    Окончание гарантии
                </th>
                <th>
                    Рабочий
                </th>
                <th>
                    Модель
                </th>
                <th>
                    Заказчик
                </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.OrderId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.OrderDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SerialNumber)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ReturnDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.WarrantyNote)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.WarrantyRepairPeriod)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Employee.FullName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Model.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Customer.FullName)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.OrderId">Редактировать</a> |
                <a asp-action="Details" asp-route-id="@item.OrderId">Детали</a> |
                <a asp-action="Delete" asp-route-id="@item.OrderId">Удалить</a>
            </td>
        </tr>
}
    </tbody>
</table>
<form asp-controller="Order" asp-action="Index">
    <p>
        Введите серийный номер <input type="text" name="SearchString">
        <input type="submit" value="Поиск" />
    </p>
</form>

@{
    var prevDisabled = !Model.HasPreviousPage ? "disabled" : "";
    var nextDisabled = !Model.HasNextPage ? "disabled" : "";
}

<a asp-action="Index"
   asp-route-page="@(Model.PageNumber - 1)"
   class="btn btn-default @prevDisabled">
    <
</a>
<a asp-action="Index"
   asp-route-page="@(Model.PageNumber + 1)"
   class="btn btn-default @nextDisabled">
    >
</a>