RepairEquipment/Models/Spare.cs
using System.ComponentModel.DataAnnotations;

namespace RepairEquipment.Models
{
    public class Spare
    {
        [Key]
        public int SpareId { get; set; }
        public int OrderId { get; set; }
        public string Name { get; set; }
        public string Functions { get; set; }
        public int Price { get; set; }

        public virtual Order Order { get; set; }
    }
}

RepairEquipment/Controllers/SpareController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using RepairEquipment.Models;
using PagedList.Core;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Authorization;

namespace RepairEquipment.Controllers
{
    [Authorize]
    public class SpareController : Controller
    {
        RepairEquipmentContext db;

        public SpareController(RepairEquipmentContext context)
        {
            db = context;
        }

        // GET: Spare
        public ActionResult Index(int? page, string searchString)
        {
            int pageSize = 10;
            int pageNumber = (page ?? 1);

            var spare = db.Spares.OrderBy(t => t.SpareId).Include(t => t.Order).ToPagedList(pageNumber, pageSize);

            if (!String.IsNullOrEmpty(searchString))
            {
                spare = db.Spares.Where(t => t.Name.Contains(searchString)).OrderBy(t => t.SpareId).Include(t => t.Order).ToPagedList(pageNumber, pageSize);
            }

            return View(spare);
        }

        // GET: Spare/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new StatusCodeResult(StatusCodes.Status400BadRequest);
            }
            Spare spare = db.Spares.Find(id);
            if (spare == null)
            {
                return NotFound();
            }
            return View(spare);
        }

        // GET: Spare/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Spare/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind("SpareId", "OrderId", "Name", "Functions", "Price")] Spare spare)
        {
            if (ModelState.IsValid)
            {
                db.Spares.Add(spare);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(spare);
        }

        // GET: Spare/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new StatusCodeResult(StatusCodes.Status400BadRequest);
            }
            Spare spare = db.Spares.Find(id);
            if (spare == null)
            {
                return NotFound();
            }
            return View(spare);
        }

        // POST: Spare/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind("SpareId", "OrderId", "Name", "Functions", "Price")] Spare spare)
        {
            if (ModelState.IsValid)
            {
                db.Entry(spare).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(spare);
        }

        // GET: Spare/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new StatusCodeResult(StatusCodes.Status400BadRequest);
            }
            Spare spare = db.Spares.Find(id);
            if (spare == null)
            {
                return NotFound();
            }
            return View(spare);
        }

        // POST: Spare/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            Spare spare = db.Spares.Find(id);
            db.Spares.Remove(spare);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

RepairEquipment/Views/Spare/Create.cshtml
@model RepairEquipment.Models.Spare

@{
    ViewData["Title"] = "Create";
}

<h2>Добавление записи</h2>

<form asp-action="Create">
    <div class="form-horizontal">
        <h4>Запчасть</h4>
        <hr />
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group">
            <label asp-for="OrderId" class="col-md-2 control-label">Номер заказа</label>
            <div class="col-md-10">
                <input asp-for="OrderId" class="form-control" />
                <span asp-validation-for="OrderId" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Name" class="col-md-2 control-label">Название</label>
            <div class="col-md-10">
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Functions" class="col-md-2 control-label">Функции</label>
            <div class="col-md-10">
                <input asp-for="Functions" class="form-control" />
                <span asp-validation-for="Functions" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Price" class="col-md-2 control-label">Цена</label>
            <div class="col-md-10">
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Добавить" class="btn btn-default" />
            </div>
        </div>
    </div>
</form>

<div>
    <a asp-action="Index">Вернуться</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

RepairEquipment/Views/Spare/Delete.cshtml
@model RepairEquipment.Models.Spare

@{
    ViewData["Title"] = "Delete";
}

<h2>Удаление записи</h2>

<h3>Вы уверены, что хотите удалить эту запись?</h3>
<div>
    <h4>Запчасть</h4>
    <hr />
    <dl class="dl-horizontal">
        <input type="hidden" asp-for="SpareId" />
        <dt>
            Номер запчасти
        </dt>
        <dd>
            @Html.DisplayFor(model => model.SpareId)
        </dd>
        <dt>
            Номер заказа
        </dt>
        <dd>
            @Html.DisplayFor(model => model.OrderId)
        </dd>
        <dt>
            Название
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt>
            Функции
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Functions)
        </dd>
        <dt>
            Цена
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <div class="form-actions no-color">
            <input type="submit" value="Удалить" class="btn btn-default" /> |
            <a asp-action="Index">Вернуться</a>
        </div>
    </form>
</div>

RepairEquipment/Views/Spare/Details.cshtml
@model RepairEquipment.Models.Spare

@{
    ViewData["Title"] = "Details";
}

<h2>Детали</h2>

<div>
    <h4>Запчасть</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Номер запчасти
        </dt>
        <dd>
            @Html.DisplayFor(model => model.SpareId)
        </dd>
        <dt>
            Номер заказа
        </dt>
        <dd>
            @Html.DisplayFor(model => model.OrderId)
        </dd>
        <dt>
            Название
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt>
            Функции
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Functions)
        </dd>
        <dt>
            Цена
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.SpareId">Редактировать</a> |
    <a asp-action="Index">Вернуться</a>
</div>

RepairEquipment/Views/Spare/Edit.cshtml
@model RepairEquipment.Models.Spare

@{
    ViewData["Title"] = "Edit";
}

<h2>Редактировать запись</h2>

<form asp-action="Edit">
    <div class="form-horizontal">
        <h4>Запчасть</h4>
        <hr />
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <input type="hidden" asp-for="SpareId" />
        <div class="form-group">
            <label asp-for="OrderId" class="col-md-2 control-label">Номер заказа</label>
            <div class="col-md-10">
                <input asp-for="OrderId" class="form-control" />
                <span asp-validation-for="OrderId" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Name" class="col-md-2 control-label">Название</label>
            <div class="col-md-10">
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Functions" class="col-md-2 control-label">Функции</label>
            <div class="col-md-10">
                <input asp-for="Functions" class="form-control" />
                <span asp-validation-for="Functions" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Price" class="col-md-2 control-label">Цена</label>
            <div class="col-md-10">
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Сохранить" class="btn btn-default" />
            </div>
        </div>
    </div>
</form>

<div>
    <a asp-action="Index">Вернуться</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

RepairEquipment/Views/Spare/Index.cshtml
@using PagedList.Core;

@model IPagedList<RepairEquipment.Models.Spare>

@{
    ViewData["Title"] = "List";
}

<h2>Запчасти</h2>

<p>
    <a asp-action="Create">Добавить запись</a>
</p>
<table class="table">
    <thead>
        <tr>
                <th>
                    Номер запчасти
                </th>
                <th>
                    Номер заказа
                </th>
                <th>
                    Название
                </th>
                <th>
                    Функции
                </th>
                <th>
                    Цена
                </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.SpareId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.OrderId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Functions)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Price)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.SpareId">Редактировать</a> |
                <a asp-action="Details" asp-route-id="@item.SpareId">Детали</a> |
                <a asp-action="Delete" asp-route-id="@item.SpareId">Удалить</a>
            </td>
        </tr>
}
    </tbody>
</table>
<form asp-controller="Spare" asp-action="Index">
    <p>
        Введите название <input type="text" name="SearchString">
        <input type="submit" value="Поиск" />
    </p>
</form>

@{
    var prevDisabled = !Model.HasPreviousPage ? "disabled" : "";
    var nextDisabled = !Model.HasNextPage ? "disabled" : "";
}

<a asp-action="Index"
   asp-route-page="@(Model.PageNumber - 1)"
   class="btn btn-default @prevDisabled">
    <
</a>
<a asp-action="Index"
   asp-route-page="@(Model.PageNumber + 1)"
   class="btn btn-default @nextDisabled">
    >
</a>