RepairEquipment/Models/Customer.cs
using System.Collections.Generic;

namespace RepairEquipment.Models
{
    public class Customer
    {
        public int CustomerId { get; set; }
        public string FullName { get; set; }
        public string HomeAddress { get; set; }
        public string PhoneNumber { get; set; }
        public virtual ICollection<Order> Orders { get; set; }
        public Customer()
        {
            Orders = new List<Order>();
        }
    }
}

RepairEquipment/Controllers/CustomerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using RepairEquipment.Models;
using PagedList.Core;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Authorization;

namespace RepairEquipment.Controllers
{
    [Authorize]
    public class CustomerController : Controller
    {
        RepairEquipmentContext db;

        public CustomerController(RepairEquipmentContext context)
        {
            db = context;
        }

        // GET: Customer
        public ActionResult Index(int? page, string searchString)
        {
            int pageSize = 10;
            int pageNumber = (page ?? 1);

            var customer = db.Customers.OrderBy(t => t.CustomerId).ToPagedList(pageNumber, pageSize);

            if (!String.IsNullOrEmpty(searchString))
            {
                customer = db.Customers.Where(t => t.FullName.Contains(searchString)).OrderBy(t => t.CustomerId).ToPagedList(pageNumber, pageSize);
            }

            return View(customer);
        }

        // GET: Customer/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new StatusCodeResult(StatusCodes.Status400BadRequest);
            }
            Customer customer = db.Customers.Find(id);
            if (customer == null)
            {
                return NotFound();
            }
            return View(customer);
        }

        // GET: Customer/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Customer/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(include: "CustomerId,FullName,HomeAddress,PhoneNumber,OrderId")] Customer customer)
        {
            try
            {
                // TODO: Add insert logic here
                db.Customers.Add(customer);
                db.SaveChanges();

                return RedirectToAction("Index");
            }
            catch
            {
                return View(customer);
            }
        }

        // GET: Customer/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new StatusCodeResult(StatusCodes.Status400BadRequest);
            }
            Customer customer = db.Customers.Find(id);
            if (customer == null)
            {
                return NotFound();
            }
            return View(customer);
        }

        // POST: Customer/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(include: "CustomerId,FullName,HomeAddress,PhoneNumber,OrderId")] Customer customer)
        {
            try
            {
                // TODO: Add update logic here
                db.Entry(customer).State = EntityState.Modified;
                db.SaveChanges();

                return RedirectToAction("Index");
            }
            catch
            {
                return View(customer);
            }
        }

        // GET: Customer/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new StatusCodeResult(StatusCodes.Status400BadRequest);
            }
            Customer customer = db.Customers.Find(id);
            if (customer == null)
            {
                return NotFound();
            }
            return View(customer);
        }

        // POST: Customer/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id)
        {
            try
            {
                // TODO: Add delete logic here
                Customer customer = db.Customers.Find(id);
                db.Customers.Remove(customer);
                db.SaveChanges();

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

RepairEquipment/Views/Customer/Create.cshtml
@model RepairEquipment.Models.Customer

@{
    ViewData["Title"] = "Create";
}

<h2>Добавление записи</h2>

<form asp-action="Create">
    <div class="form-horizontal">
        <h4>Заказчик</h4>
        <hr />
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group">
            <label asp-for="FullName" class="col-md-2 control-label">Ф.И.О</label>
            <div class="col-md-10">
                <input asp-for="FullName" class="form-control" />
                <span asp-validation-for="FullName" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="HomeAddress" class="col-md-2 control-label">Адрес</label>
            <div class="col-md-10">
                <input asp-for="HomeAddress" class="form-control" />
                <span asp-validation-for="HomeAddress" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="PhoneNumber" class="col-md-2 control-label">Телефон</label>
            <div class="col-md-10">
                <input asp-for="PhoneNumber" class="form-control" />
                <span asp-validation-for="PhoneNumber" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Добавить" class="btn btn-default" />
            </div>
        </div>
    </div>
</form>

<div>
    <a asp-action="Index">Вернуться</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

RepairEquipment/Views/Customer/Delete.cshtml
@model RepairEquipment.Models.Customer

@{
    ViewData["Title"] = "Delete";
}

<h2>Удаление записи</h2>

<h3>Вы уверены, что хотите удалить эту запись?</h3>
<div>
    <h4>Заказчик</h4>
    <hr />
    <dl class="dl-horizontal">
        <input type="hidden" asp-for="CustomerId" />
        <dt>
            Номер заказчика
        </dt>
        <dd>
            @Html.DisplayFor(model => model.CustomerId)
        </dd>
        <dt>
            Ф.И.О
        </dt>
        <dd>
            @Html.DisplayFor(model => model.FullName)
        </dd>
        <dt>
            Адрес
        </dt>
        <dd>
            @Html.DisplayFor(model => model.HomeAddress)
        </dd>
        <dt>
            Телефон
        </dt>
        <dd>
            @Html.DisplayFor(model => model.PhoneNumber)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <div class="form-actions no-color">
            <input type="submit" value="Удалить" class="btn btn-default" /> |
            <a asp-action="Index">Вернуться</a>
        </div>
    </form>
</div>

RepairEquipment/Views/Customer/Details.cshtml
@model RepairEquipment.Models.Customer

@{
    ViewData["Title"] = "Details";
}

<h2>Детали</h2>

<div>
    <h4>Заказчик</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Номер заказчика
        </dt>
        <dd>
            @Html.DisplayFor(model => model.CustomerId)
        </dd>
        <dt>
            Ф.И.О
        </dt>
        <dd>
            @Html.DisplayFor(model => model.FullName)
        </dd>
        <dt>
            Адрес
        </dt>
        <dd>
            @Html.DisplayFor(model => model.HomeAddress)
        </dd>
        <dt>
            Телефон
        </dt>
        <dd>
            @Html.DisplayFor(model => model.PhoneNumber)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.CustomerId">Редактировать</a> |
    <a asp-action="Index">Вернуться</a>
</div>

RepairEquipment/Views/Customer/Edit.cshtml
@model RepairEquipment.Models.Customer

@{
    ViewData["Title"] = "Edit";
}

<h2>Редактирование записи</h2>

<form asp-action="Edit">
    <div class="form-horizontal">
        <h4>Заказчик</h4>
        <hr />
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <input type="hidden" asp-for="CustomerId" />
        <div class="form-group">
            <label asp-for="FullName" class="col-md-2 control-label">Ф.И.О</label>
            <div class="col-md-10">
                <input asp-for="FullName" class="form-control" />
                <span asp-validation-for="FullName" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="HomeAddress" class="col-md-2 control-label">Адрес</label>
            <div class="col-md-10">
                <input asp-for="HomeAddress" class="form-control" />
                <span asp-validation-for="HomeAddress" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="PhoneNumber" class="col-md-2 control-label">Телефон</label>
            <div class="col-md-10">
                <input asp-for="PhoneNumber" class="form-control" />
                <span asp-validation-for="PhoneNumber" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Сохранить" class="btn btn-default" />
            </div>
        </div>
    </div>
</form>

<div>
    <a asp-action="Index">Вернуться</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

RepairEquipment/Views/Customer/Index.cshtml
@using PagedList.Core;

@model IPagedList<RepairEquipment.Models.Customer>

<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />

@{
    ViewData["Title"] = "Index";
}

<h2>Заказчики</h2>

<p>
    <a asp-action="Create">Добавить запись</a>
</p>
<table class="table">
    <thead>
        <tr>
                <th>
                    Номер заказчика
                </th>
                <th>
                    Ф.И.О
                </th>
                <th>
                    Адрес
                </th>
                <th>
                    Телефон
                </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.CustomerId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FullName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.HomeAddress)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PhoneNumber)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.CustomerId">Редактировать</a> |
                <a asp-action="Details" asp-route-id="@item.CustomerId">Детали</a> |
                <a asp-action="Delete" asp-route-id="@item.CustomerId">Удалить</a>
            </td>
        </tr>
}
    </tbody>
</table>
<form asp-controller="Customer" asp-action="Index">
    <p>
        Введите Ф.И.О <input type="text" name="SearchString">
        <input type="submit" value="Поиск" />
    </p>
</form>

@{
    var prevDisabled = !Model.HasPreviousPage ? "disabled" : "";
    var nextDisabled = !Model.HasNextPage ? "disabled" : "";
}

<a asp-action="Index"
   asp-route-page="@(Model.PageNumber - 1)"
   class="btn btn-default @prevDisabled">
    <
</a>
<a asp-action="Index"
   asp-route-page="@(Model.PageNumber + 1)"
   class="btn btn-default @nextDisabled">
    >
</a>