RepairEquipment/Models/Malfunction.cs
using System.ComponentModel.DataAnnotations;

namespace RepairEquipment.Models
{
    public class Malfunction
    {
        [Key]
        public int MalfunctionId { get; set; }
        public int OrderId { get; set; }
        public string Name { get; set; }
        public string RepairMethods { get; set; }
        public int WorkPrice { get; set; }

        public virtual Order Order { get; set; }
    }
}

RepairEquipment/Controllers/MalfunctionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using RepairEquipment.Models;
using PagedList.Core;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace RepairEquipment.Controllers
{
    [Authorize]
    public class MalfunctionController : Controller
    {
        RepairEquipmentContext db;

        public MalfunctionController(RepairEquipmentContext context)
        {
            db = context;
        }

        // GET: Malfunction
        public ActionResult Index(int? page, string searchString)
        {
            int pageSize = 10;
            int pageNumber = (page ?? 1);

            var malfunction = db.Malfunctions.OrderBy(t => t.MalfunctionId).Include(t => t.Order).ToPagedList(pageNumber, pageSize);

            if (!String.IsNullOrEmpty(searchString))
            {
                malfunction = db.Malfunctions.Where(t => t.Name.Contains(searchString)).OrderBy(t => t.MalfunctionId).Include(t => t.Order).ToPagedList(pageNumber, pageSize);
            }

            return View(malfunction);
        }

        // GET: Malfunction/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new StatusCodeResult(StatusCodes.Status400BadRequest);
            }
            Malfunction malfunction = db.Malfunctions.Find(id);
            if (malfunction == null)
            {
                return NotFound();
            }
            return View(malfunction);
        }

        // GET: Malfunction/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Malfunction/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind("MalfunctionId","OrderId","Name","RepairMethods","WorkPrice")] Malfunction malfunction)
        {
            if (ModelState.IsValid)
            {
                db.Malfunctions.Add(malfunction);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(malfunction);
        }

        // GET: Malfunction/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new StatusCodeResult(StatusCodes.Status400BadRequest);
            }
            Malfunction malfunction = db.Malfunctions.Find(id);
            if (malfunction == null)
            {
                return NotFound();
            }
            return View(malfunction);
        }

        // POST: Malfunction/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind("MalfunctionId", "OrderId", "Name", "RepairMethods", "WorkPrice")] Malfunction malfunction)
        {
            if (ModelState.IsValid)
            {
                db.Entry(malfunction).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(malfunction);
        }

        // GET: Malfunction/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new StatusCodeResult(StatusCodes.Status400BadRequest);
            }
            Malfunction malfunction = db.Malfunctions.Find(id);
            if (malfunction == null)
            {
                return NotFound();
            }
            return View(malfunction);
        }

        // POST: Malfunction/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            Malfunction malfunction = db.Malfunctions.Find(id);
            db.Malfunctions.Remove(malfunction);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

RepairEquipment/Views/Malfunction/Create.cshtml
@model RepairEquipment.Models.Malfunction

@{
    ViewData["Title"] = "Create";
}

<h2>Добавление записи</h2>

<form asp-action="Create">
    <div class="form-horizontal">
        <h4>Неисправность</h4>
        <hr />
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group">
            <label asp-for="OrderId" class="col-md-2 control-label">Номер заказа</label>
            <div class="col-md-10">
                <input asp-for="OrderId" class="form-control" />
                <span asp-validation-for="OrderId" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Name" class="col-md-2 control-label">Название</label>
            <div class="col-md-10">
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="RepairMethods" class="col-md-2 control-label">Методы починки</label>
            <div class="col-md-10">
                <input asp-for="RepairMethods" class="form-control" />
                <span asp-validation-for="RepairMethods" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="WorkPrice" class="col-md-2 control-label">Цена</label>
            <div class="col-md-10">
                <input asp-for="WorkPrice" class="form-control" />
                <span asp-validation-for="WorkPrice" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Добавление" class="btn btn-default" />
            </div>
        </div>
    </div>
</form>

<div>
    <a asp-action="Index">Вернуться</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

RepairEquipment/Views/Malfunction/Delete.cshtml
@model RepairEquipment.Models.Malfunction

@{
    ViewData["Title"] = "Delete";
}

<h2>Удаление записи</h2>

<h3>Вы уверены, что хотите удалить эту запись?</h3>
<div>
    <h4>Неисправность</h4>
    <hr />
    <dl class="dl-horizontal">
        <input type="hidden" asp-for="MalfunctionId" />
        <dt>
            Номер неисправности
        </dt>
        <dd>
            @Html.DisplayFor(model => model.MalfunctionId)
        </dd>
        <dt>
            Номер заказа
        </dt>
        <dd>
            @Html.DisplayFor(model => model.OrderId)
        </dd>
        <dt>
            Название
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt>
            Методы починки
        </dt>
        <dd>
            @Html.DisplayFor(model => model.RepairMethods)
        </dd>
        <dt>
            Цена
        </dt>
        <dd>
            @Html.DisplayFor(model => model.WorkPrice)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <div class="form-actions no-color">
            <input type="submit" value="Удалить" class="btn btn-default" /> |
            <a asp-action="Index">Вернуться</a>
        </div>
    </form>
</div>

RepairEquipment/Views/Malfunction/Details.cshtml
@model RepairEquipment.Models.Malfunction

@{
    ViewData["Title"] = "Details";
}

<h2>Детали</h2>

<div>
    <h4>Неисправность</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Номер неисправности
        </dt>
        <dd>
            @Html.DisplayFor(model => model.MalfunctionId)
        </dd>
        <dt>
            Номер заказа
        </dt>
        <dd>
            @Html.DisplayFor(model => model.OrderId)
        </dd>
        <dt>
            Название
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt>
            Методы починки
        </dt>
        <dd>
            @Html.DisplayFor(model => model.RepairMethods)
        </dd>
        <dt>
            Цена
        </dt>
        <dd>
            @Html.DisplayFor(model => model.WorkPrice)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.MalfunctionId">Редактировать</a> |
    <a asp-action="Index">Вернуться</a>
</div>

RepairEquipment/Views/Malfunction/Edit.cshtml
@model RepairEquipment.Models.Malfunction

@{
    ViewData["Title"] = "Edit";
}

<h2>Редактировать запись</h2>

<form asp-action="Edit">
    <div class="form-horizontal">
        <h4>Неисправность</h4>
        <hr />
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <input type="hidden" asp-for="MalfunctionId" />
        <div class="form-group">
            <label asp-for="OrderId" class="col-md-2 control-label">Номер заказа</label>
            <div class="col-md-10">
                <input asp-for="OrderId" class="form-control" />
                <span asp-validation-for="OrderId" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Name" class="col-md-2 control-label">Название</label>
            <div class="col-md-10">
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="RepairMethods" class="col-md-2 control-label">Методы починки</label>
            <div class="col-md-10">
                <input asp-for="RepairMethods" class="form-control" />
                <span asp-validation-for="RepairMethods" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="WorkPrice" class="col-md-2 control-label">Цена</label>
            <div class="col-md-10">
                <input asp-for="WorkPrice" class="form-control" />
                <span asp-validation-for="WorkPrice" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Сохранить" class="btn btn-default" />
            </div>
        </div>
    </div>
</form>

<div>
    <a asp-action="Index">Вернуться</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

RepairEquipment/Views/Malfunction/Index.cshtml
@using PagedList.Core;

@model IPagedList<RepairEquipment.Models.Malfunction>

@{
    ViewData["Title"] = "List";
}

<h2>Неисправности</h2>

<p>
    <a asp-action="Create">Добавить запись</a>
</p>
<table class="table">
    <thead>
        <tr>    
                <th>
                    Номер неисправности
                </th>
                <th>
                    Номер заказа
                </th>
                <th>
                    Название
                </th>
                <th>
                    Методы починки
                </th>
                <th>
                    Цена
                </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.MalfunctionId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.OrderId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.RepairMethods)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.WorkPrice)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.MalfunctionId">Редактировать</a> |
                <a asp-action="Details" asp-route-id="@item.MalfunctionId">Детали</a> |
                <a asp-action="Delete" asp-route-id="@item.MalfunctionId">Удалить</a>
            </td>
        </tr>
}
    </tbody>
</table>
<form asp-controller="Malfunction" asp-action="Index">
    <p>
        Введите название <input type="text" name="SearchString">
        <input type="submit" value="Поиск" />
    </p>
</form>

@{
    var prevDisabled = !Model.HasPreviousPage ? "disabled" : "";
    var nextDisabled = !Model.HasNextPage ? "disabled" : "";
}

<a asp-action="Index"
   asp-route-page="@(Model.PageNumber - 1)"
   class="btn btn-default @prevDisabled">
    <
</a>
<a asp-action="Index"
   asp-route-page="@(Model.PageNumber + 1)"
   class="btn btn-default @nextDisabled">
    >
</a>